Return error for invalid exports
denoland/deno_package_json pull request #5
Opened 2024-10-05 02:57 UTC by littledivy

https://github.com/denoland/deno/issues/26031

2024-10-05 03:06 UTC, littledivy commented
cc @dsherret 

(btw i dont have write access to repo)

2024-10-05 03:10 UTC, littledivy commented
btw thoughts on merging this crate into `deno_config`? a change to this crate has to go through 3 PRs to make it into Deno

2024-10-05 07:39 UTC, dsherret commented on src/lib.rs
> +  InvalidExports,
I'm not sure we want to do this here. Isn't this error already surfaced during resolution?

2024-10-05 07:40 UTC, dsherret commented on src/lib.rs
> +  InvalidExports,
Oh, it's currently a panic lol

2024-10-05 07:42 UTC, dsherret commented
> thoughts on merging this crate into deno_config

It's very rare to update this crate and this is used without deno_config in node_resolver. Maybe if we updated the deno_config repo to be able to publish multiple crates, but I think it's not worth the effort atm.

2024-10-13 10:23 UTC, littledivy commented
@dsherret PTAL

2024-10-18 13:19 UTC, dsherret requested changes
Can we investigate shifting this to be done only when resolving the exports? That way we can load invalid package.json files.

2025-02-24 15:45 UTC, dsherret commented
I looked a bit into this, and I don't think it's worth the effort to do it lazily. Going to merge.

2025-02-24 15:46 UTC, dsherret approved these changes
LGTM

2025-02-24 15:48 UTC, merged